name: ASCII Artwork

on: push

jobs:

  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v7

      - name: Checkout Repo files
        run: ls -latrh

      - name: Run ASCII Script
        run: |
            chmod +x ascii.sh
            ./ascii.sh
      

