name: Matrix Configurations

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 6 # max number of jobs allowed to run in parallel
            matrix:
                os_name: [ubuntu-latest, windows-latest]
                images_name: [hello-world, alpine]

                exclude:
                    - images_name: alpine
                      os_name: windows-latest
                include:
                    - images_name: amd64/alpine
                      os_name: ubuntu-latest

        runs-on: ${{ matrix.os_name }}
        steps:
            - name: Docker Details
              run: docker info

            - name: Run Image on ${{ matrix.os_name }}
              run: docker run ${{ matrix.images_name }}